# Generated by Django 4.1 on 2022-08-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
